src/13618/ko_KR-w8385.json
`문제`의 세 번째 문단, 네 번째 문단 그리고 `입력`을 의역했습니다.
=> Add 13618 w8385

src/15474/ko_KR-kiwiyou.html, src/18412/ko_KR-ez_code.html, src/24078/ko_KR-kiwiyou.html, src/24082/ko_KR-ez_code.html, src/24084/ko_KR-ez_code.html, src/24086/ko_KR-kiwiyou.html, src/27324/ko_KR-kiwiyou.html, src/27327/ko_KR-kiwiyou.html, src/27328/ko_KR-kiwiyou.html, src/27331/ko_KR-kiwiyou.html, src/27332/ko_KR-kiwiyou.html, src/27541/ko_KR-kiwiyou.html
=> fix 15474, 18412, 24078, 24082, 24084, 24086, 27324, 27327, 27328, 27331, 27332, 27541

index, src/26665/ko_KR-pasteldream.html, src/7964/ko_KR-pasteldream.html
- [o] Did you stage index file?
- [o] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [o] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?
=> Add 7964, 26665

src/27331/ko_KR-kiwiyou.html
- [v] Did you stage index file?
- [v] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [v] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?
=> Fix minor typo in 27331

index, src/24860/ko_KR-DoubleDeltas.html
- [v] Did you stage index file?
- [v] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [v] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?
24860번([Counting Antibodies](https://www.acmicpc.net/problem/24860)) 번역했습니다.
=> feat: translated problem 24860

index, src/13742/ko_KR-leeunchong.html
=> 13742번 번역입니다.

src/10671/ko_KR-biximo.html
=> 10671 한글어로 번역 

src/26969/ko_KR-kiwiyou.html
=> 입력 부분의 $P_i$, $P_i$, $C_i$ - > $P_i$, $C_i$, $X_i$ 수정

index, src/1157/en_US-masooka.html
=> Add en_US 1157

index, src/10809/en_US-masooka.html
=> Add en_US 10809

index, src/2577/en_US-masooka.html
=> Add en_US 2577

index, src/1152/en_US-masooka.html
=> Add en_US 1152

index, src/10818/en_US-masooka.html
=> Add en_US 10818

index, src/11720/en_US-masooka.html
=> Add en_US 11720

index, src/2438/en_US-masooka.html
=> Add en_US 2438

index, src/2439/en_US-masooka.html
=> Add en_US 2439

index, src/25083/en_US-masooka.html
=> Add en_US 25083

index, src/11654/en_US-masooka.html
=> Add en_US 11654

index, src/2741/en_US-masooka.html
=> Add en_US 2741

index, src/10950/en_US-masooka.html
=> Add en_US 10950

index, src/2753/en_US-masooka.html
=> Add en_US 2753

index, src/2739/en_US-masooka.html
=> Add en_US 2739

index, src/2440/en_US-masooka.html
=> Add en_US 2440

index, src/27335/ko_KR-dbrua1222.html
=> 27335 ko_KR

index, src/10951/en_US-masooka.html
=> Add en_US 10951

index, src/10952/en_US-masooka.html
=> Add en_US 10952

index, src/10871/en_US-masooka.html
=> Add en_US 10871

index, src/11050/en_US-masooka.html
=> Add en_US 11050

index, src/13305/en_US-masooka.html
=> Add en_US 13305

index, src/2750/en_US-masooka.html
=> Add en_US 2750

index, src/10828/en_US-masooka.html
=> Add en_US 10828

index, src/2751/en_US-masooka.html
=> Add en_US 2751

index, src/2609/en_US-masooka.html
=> Add en_US 2609

index, src/10989/en_US-masooka.html
=> Add en_US 10989

index, src/1546/en_US-masooka.html
=> Add en_US 1546

index, src/7568/en_US-masooka.html
=> Add en_US 7568

index, src/11866/en_US-masooka.html
=> Add en_US 11866

index, src/10814/en_US-masooka.html
=> Add en_US 10814

index, src/10845/en_US-masooka.html
=> Add en_US 10845

index, src/2775/en_US-masooka.html
=> Add en_US 2775

index, src/7569/en_US-masooka.html
=> Add en_US 7569

index, src/1676/en_US-masooka.html
=> Add en_US 1676

index, src/2108/en_US-masooka.html
=> Add en_US 2108

index, src/1003/en_US-masooka.html
=> Add en_US 1003

index, src/11650/en_US-masooka.html
=> Add en_US 11650

index, src/10866/en_US-masooka.html
=> Add en_US 10866

index, src/2164/en_US-masooka.html
=> Add en_US 2164

index, src/1181/en_US-masooka.html
=> Add en_US 1181

index, src/1018/en_US-masooka.html
=> Add en_US 1018

index, src/10816/en_US-masooka.html
=> Add en_US 10816

index, src/20060/ko_KR-ldhhello.html, src/24080/ko_KR-ldhhello.html, src/26495/ko_KR-ldhhello.html
=> 20060, 24080, 26495 번역입니다!!

index, src/30300/ko_KR-wizardrabbit.html, src/31275/ko_KR-wizardrabbit.html
안녕하세요!
두 문제 간단하게 번역하고 왔습니다~
- 30300번 ([문제](https://icpc.me/30300) / [번역](https://www.acmicpc.net/board/view/131808))
- 31275번 ([문제](https://icpc.me/31275) / [번역](https://www.acmicpc.net/board/view/134913))
=> Add 30300, 31275 wizardrabbit

index, src/29517/ko_KR-wizardrabbit.html, src/6167/ko_KR-wizardrabbit.html
안녕하세요!
두 문제 번역 진행했습니다!
- 29517번 ([문제](https://icpc.me/29517) / [번역](https://www.acmicpc.net/board/view/135335))
- 6167번 ([문제](https://icpc.me/6167) / [번역](https://www.acmicpc.net/board/view/136126))
=> Add 29517, 6167 wizardrabbit

index, src/31262/ko_KR-halin.html
=> add 31262 ko_KR halin

src/24758/ko_KR-w8385.html
안녕하세요!
이번에는 새로운 번역이 아니라, 번역 수정 PR입니다!
1. 수정한 번역: `24758`번 문제, by `w8385`님
2. 수정 내용:
- 입력 조건을 $10^9$ 에서 $10^{12}$ 로 올바르게 수정
- `o-ey`의 포맷팅 규칙에 맞게 포맷팅
감사합니다!
=> Fix 24758 w8385

index, src/20470/ko_KR-wizardrabbit.html, src/24852/ko_KR-wizardrabbit.html
안녕하세요!
오늘은 짧은 번역 2개 들고 왔습니다!
- [**20470**](https://icpc.me/20470)
- [**24852**](https://icpc.me/24852) -- [**번역**](https://www.acmicpc.net/board/view/138916)
=> Add 20470, 24852 wizardrabbit

index, src/12070/ko_KR-wizardrabbit.html, src/19778/ko_KR-wizardrabbit.html, src/19880/ko_KR-wizardrabbit.html, src/22066/ko_KR-wizardrabbit.html, src/23878/ko_KR-wizardrabbit.html, src/27263/ko_KR-wizardrabbit.html
📕이번에는 번역 $6$개입니다! 잘 부탁드립니다
| 문제 번호                                     | 새로운 문제 제목 / 번역 게시글 링크                                                  |
|:------------------------------------:|---------------------------------------------------------------------------|
| [23878](https://icpc.me/23878)   | [외로운 구간](https://www.acmicpc.net/board/view/141683)              |
| [19880](https://icpc.me/19880)   | [페이지 번호](https://www.acmicpc.net/board/view/141836)                   |
| [22066](https://icpc.me/22066)   | [기간제 버스 카드](https://www.acmicpc.net/board/view/141917)                 |
| [27263](https://icpc.me/27263)   | [고대 영어로 변환하기](https://www.acmicpc.net/board/view/142043)                     | 
| [19778](https://icpc.me/19778)   | [고리 던지기 게임](https://www.acmicpc.net/board/view/143265) …
=> Add 23878, 19880, 22066, 27263, 19778, 12070 ko_KR wizardrabbit

index, src/13083/ko_KR-wizardrabbit.html, src/27542/ko_KR-wizardrabbit.html, src/8029/ko_KR-wizardrabbit.html
📕이번에는 번역 $3$개입니다! 잘 부탁드립니다
| 문제 번호                                     | 새로운 문제 제목 / 번역 게시글 링크                                                  |
|:------------------------------------:|---------------------------------------------------------------------------|
| [8029](https://icpc.me/8029)   | [거리가 R 이하인 1의 개수](https://www.acmicpc.net/board/view/144786)              |
| [13083](https://icpc.me/13083)   | [비밀번호 변경하기](https://www.acmicpc.net/board/view/144835)                   |
| [27542](https://icpc.me/27542)   | [절댓값 수열](https://www.acmicpc.net/board/view/144843)                 |
항상 고생이 많으세요
=> Add 8029, 13083, 27542 ko_KR wizardrabbit

index, src/18674/ko_KR-pajarito.html
---
- 목록
| 번호 | 원제목 | 번역 |
|:---:|:---|:---|
| [18674](https://www.acmicpc.net/problem/18674) | [The Minions Quiz](https://www.acmicpc.net/problem/18674) | 미니언즈 퀴즈 |
혹시 잘못된 부분 있으면 알려주세요.
감사합니다 : )
=> add 18674 (ko_KR) pajarito

index, src/5591/ko_KR-pajarito.html
---
- 목록
| 번호 | 원제목 | 번역 |
|:---:|:---|:---|
| [5591](https://www.acmicpc.net/problem/5591) | [最大の和](https://www.acmicpc.net/problem/5591) | 최대합 |
잘못된 부분 있으면 알려주세요.
항상 감사드립니다 : )
=> Add 5591 (ko_KR) pajarito

index, src/31611/ko_KR-pajarito.html
---
- 목록
| 번호 | 원제목 | 번역 |
|:---:|:---|:---|
| [31611](https://www.acmicpc.net/problem/31611) | [火曜日 (Tuesday)](https://www.acmicpc.net/problem/31611) | 화요일 |
잘못된 부분 있으면 알려주세요.
항상 감사드립니다 : )
=> Add 31611 (ko_KR) pajarito

index, src/18110/en_US-masooka.html
=> Add en_US 18110

.gitignore, index, src/16654/ko_KR-BothEarRim.html
처음 번역 기여해봅니다. 혹시 잘못된 부분 있다면 말씀해주시면 수정하겠습니다.
PyCharm으로 작업하는데 `.idea` 등 때문에 `.gitignore` 항목도 추가했습니다.
|문제 번호|새로운 문제 제목|
|-|-|
|[16654](https://boj.kr/16654)|일반화된 독일어 따옴표|
=> Add 16654 ko_KR BothEarRim
